language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode

before_install:
  - curl -L https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.9/
  - make
  - ./beanstalkd &
  - cd $TRAVIS_BUILD_DIR

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
